import { createRecipeGraph } from '../src';
import {
  DiagnosticEntry,
  DiagnosticManualNote,
  createDiagnosticInventoryStateKey,
  parseDiagnosticNdjson,
  parseStoredZipFiles,
} from '../src/diagnostic-match-parser';

const EXTRA_REGEN = { id: 2829638276, name: 'Extra Regen', class_name: 'upgrade_endurance' };
const HIGH_VELOCITY = { id: 3077079169, name: 'High-Velocity Rounds', class_name: 'upgrade_high_velocity_mag' };
const OPENING_ROUNDS = { id: 2064029594, name: 'Opening Rounds', class_name: 'upgrade_pristine_emblem' };

describe('diagnostic match parser', () => {
  it('parses a local purchase and confirms a marker-backed sale', () => {
    const entries = [
      entry(1, 'match_id', '94179501'),
      entry(2, 'roster_12', { steam_id: '76561198066539144', player_name: 'Chewbacca', hero_id: 72, hero_name: 'BILLY', team_id: 3, is_local: true }),
      entry(3, 'roster_1', { steam_id: '0', player_name: 'Enemy Bot', hero_id: 10, team_id: 2, is_local: false }),
      entry(4, 'match_clock', '1:39'),
      entry(5, 'items_12', { steam_id: '76561198066539144' }),
      entry(6, 'match_clock', '1:40'),
      entry(7, 'items_12', { steam_id: '76561198066539144', items: [EXTRA_REGEN] }),
      entry(8, 'match_clock', '1:44'),
      entry(9, 'items_12', { steam_id: '76561198066539144', items: [] }),
    ];
    const notes: DiagnosticManualNote[] = [{
      id: 'sell-extra-regen',
      createdAt: '2026-07-16T23:54:09.000Z',
      approximateGameTime: '1:44',
      action: 'SELL',
      item: 'Extra Regen',
    }];

    const result = parseDiagnosticNdjson(toNdjson(entries), { manualNotes: notes });
    const match = result.matches[0];
    const localActions = match.timelines.find((timeline) => timeline.player.isLocal)?.actions ?? [];

    expect(match.matchId).toBe('94179501');
    expect(match.localPlayerKey).toBe('76561198066539144');
    expect(localActions.map((action) => action.type)).toEqual(['RECONCILE', 'BUY', 'SELL']);
    expect(localActions[localActions.length - 1]).toMatchObject({
      itemId: EXTRA_REGEN.id,
      markerId: 'sell-extra-regen',
      markerConfirmed: true,
      beforeStateKey: `${EXTRA_REGEN.id}x1`,
      afterStateKey: 'EMPTY',
    });
    expect(match.markerResults).toEqual([expect.objectContaining({ status: 'MATCHED', playerKey: '76561198066539144' })]);
    expect(match.trainingExamples.map((example) => example.actionKey)).toEqual([
      `BUY:${EXTRA_REGEN.id}`,
      `SELL:${EXTRA_REGEN.id}`,
    ]);
    expect(match.trainingExamples[match.trainingExamples.length - 1]).toMatchObject({
      heroId: 72,
      enemyHeroIds: [10],
      phase: 'EARLY',
      markerConfirmed: true,
    });
  });

  it('infers an upgrade but never fabricates an action from a wrong marker', () => {
    const entries = [
      entry(1, 'match_id', '93314383'),
      entry(2, 'roster_12', { steam_id: '76561198066539144', hero_id: 72, team_id: 3, is_local: true }),
      entry(3, 'match_clock', '5:00'),
      entry(4, 'items_12', { steam_id: '76561198066539144', items: [HIGH_VELOCITY] }),
      entry(5, 'match_clock', '5:01'),
      entry(6, 'items_12', { steam_id: '76561198066539144', items: [OPENING_ROUNDS] }),
    ];
    const notes: DiagnosticManualNote[] = [{
      id: 'wrong-rapid-recharge',
      createdAt: '2026-07-16T23:54:06.000Z',
      approximateGameTime: '5:01',
      action: 'SELL',
      item: 'Rapid Recharge',
    }];
    const recipeGraph = createRecipeGraph([{ parentItemId: OPENING_ROUNDS.id, componentItemIds: [HIGH_VELOCITY.id] }]);

    const result = parseDiagnosticNdjson(toNdjson(entries), { manualNotes: notes, recipeGraph });
    const local = result.matches[0].timelines.find((timeline) => timeline.player.isLocal);

    expect(local?.actions.map((action) => action.type)).toEqual(['RECONCILE', 'UPGRADE']);
    expect(local?.finalStateKey).toBe(`${OPENING_ROUNDS.id}x1`);
    expect(result.markerResults).toEqual([
      expect.objectContaining({ note: expect.objectContaining({ id: 'wrong-rapid-recharge' }), status: 'UNMATCHED' }),
    ]);
    expect(result.matches[0].trainingExamples).toEqual([
      expect.objectContaining({
        actionKey: `UPGRADE:${OPENING_ROUNDS.id}`,
        beforeStateKey: `${HIGH_VELOCITY.id}x1`,
        afterStateKey: `${OPENING_ROUNDS.id}x1`,
        markerConfirmed: false,
      }),
    ]);
  });

  it('parses the stored ZIP format generated by the diagnostic client', () => {
    const files = parseStoredZipFiles(createStoredZip([
      { name: 'overwolf-events.ndjson', content: '{"sequence":1}\n' },
      { name: 'notes.json', content: '[]' },
    ]));
    expect(new TextDecoder().decode(files.get('overwolf-events.ndjson'))).toBe('{"sequence":1}\n');
    expect(new TextDecoder().decode(files.get('notes.json'))).toBe('[]');
  });

  it('canonicalizes duplicate inventory item counts', () => {
    expect(createDiagnosticInventoryStateKey([20, 10, 20])).toBe('10x1|20x2');
  });
});

function entry(sequence: number, key: string, payload: unknown): DiagnosticEntry {
  return {
    sequence,
    appSessionId: 'session-test',
    receivedAt: new Date(Date.UTC(2026, 6, 16, 23, 54, sequence)).toISOString(),
    source: key === 'match_clock' ? 'onNewEvents' : 'onInfoUpdates2',
    category: key.startsWith('items_') ? 'items' : key.startsWith('roster_') ? 'roster' : 'match_info',
    key,
    rawPayload: JSON.stringify(payload),
  };
}

function toNdjson(entries: readonly DiagnosticEntry[]): string {
  return entries.map((value) => JSON.stringify(value)).join('\n');
}

function createStoredZip(files: Array<{ name: string; content: string }>): Uint8Array {
  const encoder = new TextEncoder();
  const parts: Uint8Array[] = [];
  for (const file of files) {
    const name = encoder.encode(file.name);
    const content = encoder.encode(file.content);
    const header = new Uint8Array(30 + name.length);
    const view = new DataView(header.buffer);
    view.setUint32(0, 0x04034b50, true);
    view.setUint16(4, 20, true);
    view.setUint16(6, 0x0800, true);
    view.setUint16(8, 0, true);
    view.setUint32(18, content.length, true);
    view.setUint32(22, content.length, true);
    view.setUint16(26, name.length, true);
    header.set(name, 30);
    parts.push(header, content);
  }
  const result = new Uint8Array(parts.reduce((sum, part) => sum + part.length, 0));
  let offset = 0;
  for (const part of parts) {
    result.set(part, offset);
    offset += part.length;
  }
  return result;
}
